name: Schedule Cleaning Events

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering via GitHub UI

jobs:
  schedule-cleaning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run Python script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      run: python main.py

    # Store token.json securely without printing it in logs
    - name: Update TOKEN_JSON secret
      run: |
        gh secret set TOKEN_JSON --body "$(cat token.json)" > /dev/null 2>&1