name: Schedule Cleaning Events

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  schedule-cleaning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run Python script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      run: python main.py

    - name: Store token.json as secret
      if: success()
      run: |
        echo "::set-output name=TOKEN_JSON::$(cat token.json)"
      id: store-token

    - name: Update TOKEN_JSON secret
      uses: peter-evans/create-or-update-secret-action@v2
      with:
        secret: TOKEN_JSON
        token: ${{ secrets.GITHUB_TOKEN }}
        value: ${{ steps.store-token.outputs.TOKEN_JSON }}